Revert "MSI Installer for QLDB Shell (#61)"
This reverts commit 06e8c51ef67a95ad1d1eb35bfe81115cda00a8bc.

This is breaking our releases:

https://github.com/awslabs/amazon-qldb-shell/runs/2515614145?check_suite_focus=true

```
main.wxs
D:\a\amazon-qldb-shell\amazon-qldb-shell\wix\main.wxs(34) : error CNDL0108 : The Product/@Version attribute's value, '2.0.0-alpha7', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
D:\a\amazon-qldb-shell\amazon-qldb-shell\wix\main.wxs(34) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
Error[1] (Command): The 'candle' application failed with exit code = 10

Error: Process completed with exit code 1.
```

Probably a silly issue, but we want to get a fix .exe out to help debug
CloudShell issues.